name: test

# if set to a specific path, model predictions will be saved to this path
# with the filename format: 
#  - (optional) ground truth: {predict_output_dir}/{ckpt-name}/gt/images/{image-name}.png
#  - (optional) ground truth masks: {predict_output_dir}/{ckpt-name}/gt/masks/{image-name}.png
#  - predicted masks: {predict_output_dir}/{ckpt-name}/mask/{image-name}.png
#  - predicted labels: {predict_output_dir}/{ckpt-name}/predictions.txt
# in predictions.txt, each line is {image-name}.png,{probs to be forged:.4f} 
pred_output_dir: null

output_gt: false
enable_tta: false

# a float between 0 and 1, if predicted probability is greater than this value, the image will be classified as forged
# and the corresponding predicted mask will be zeros.
trust_classifier: 0.5