name: test

# if set to a specific path, model predictions will be saved to this path
# with the filename format: 
#  - predicted masks: {predict_output_dir}/{ckpt-name}/masks/{image-name}.png
#  - predicted labels: {predict_output_dir}/{ckpt-name}/predictions.txt
# in predictions.txt, each line is {image-name}.png,{probs to be forged:.4f} 
pred_output_dir: null

enable_tta: false