defaults:
  - cls_seg
  - _self_
  
# list of checkpoints to load, the latter will override the former
# must end with .safetensors or .pt/.pth
checkpoint_paths: ["checkpoints/cls/model.safetensors", "checkpoints/seg/model.safetensors"]