defaults:
  - base
  - _self_

# loupe configs
cls_mlp_ratio: 2 # 2 times of Perception Encoder output dim
cls_mlp_layers: 2
enable_patch_cls: True
enable_cls_fusion: True

freeze_cls: False
freeze_backbone: True

cls_forge_weight: 0.2
patch_forge_weight: 0.85
