defaults:
  - cls
  - seg
  - _self_

freeze_backbone: False
freeze_cls: False
freeze_seg: False

cls_loss_weight: 2.0
seg_loss_weight: 1.0

# conditional_queries is typically used for test-time adaptation
# during segmentation training, conditional_queries will serve as an
# extra condition provided for pixel decoder.
enable_conditional_queries: True