defaults:
  - default
  - _self_

fpn_scales: [0.5, 2] # rescale the last hidden states of backbone. for PE-Core-L14-336, rescale to 12x12, 48x48, 96x96
freeze_backbone: True
freeze_seg: False

backbone_path: /gemini/code/loupe/checkpoints/cls/model.safetensors # if can also be a path to a cls checkpoint

mask2former_path: null
# mask2former overrides, you can set attr to '-' to use default value
mask2former_overrides:
  num_labels: 1
  common_stride: "-" # the stride of the last feature map, for PE-Core-L14-336, it is its patch size, 14
  feature_strides: "-" # the strides of feature maps after fpn scaling
  feature_size: "-" # the final output dim of backbone, for PE-Core-L14-336, it is 1024

