defaults:
  - base
  - _self_

fpn_scales: [0.5, 2, 4] # rescale the last hidden states of backbone. for PE-Core-L14-336, rescale to 12x12, 48x48, 96x96
freeze_backbone: True
freeze_seg: False
# tversky alpha and beta control the weight of false positive and false negative, respectively
# the tversky beta is set to 1 - alpha
tversky_alpha: 0.3
# weight for forged pixels, set between 0 and 1
pixel_forge_weight: 0.8
# epsilon for poly1 focal loss
pixel_poly_epsilon: 1.0

# conditional_queries is typically used for test-time adaptation
# during segmentation training, conditional_queries will serve as an
# extra condition provided for pixel decoder.
enable_conditional_queries: True

# mask2former overrides, you can set attr to '-' to use default value
# visit https://huggingface.co/docs/transformers/main/model_doc/mask2former#transformers.Mask2FormerConfig for available overrides
mask2former_overrides:
  num_queries: 20
  mask_weight: 5
  class_weight: 2
  dice_weight: 5
  id2label:
    0: "forgery"
  label2id:
    forgery: 0

