defaults:
  - default
  - _self_

fpn_scales: [0.5, 2] # rescale the last hidden states of backbone. for PE-Core-L14-336, rescale to 12x12, 48x48, 96x96
freeze_backbone: True
freeze_seg: False

backbone_path: /gemini/code/loupe/checkpoints/cls/model.safetensors # if can also be a path to a cls checkpoint

mask2former_path: /gemini/code/loupe/pretrained_weights/mask2former
# mask2former overrides, you can set attr to '-' to use default value
mask2former_overrides:
  num_labels: 1
  id2label:
    0: "forgery"
  label2id:
    forgery: 0

