seed: 42
trainer:
  precision: 16-mixed
  strategy: deepspeed_stage_2_offload # options: "deepspeed_stage_2_offload" / "ddp"
  fast_dev_run: false # set to true for debugging
hydra.output_subdir: null