model_config:
  _target_: "src.models.loupe.LoupeConfig"
  backbone_name: PE-Core-L14-336
  pretrained_path: /gemini/code/loupe/pretrained_weights/pe/PE-Core-L14-336.pt
  hidden_act: "gelu"
  hidden_dropout_prob: 0.1
  initializer_range: 0.02
  cls_mlp_hidden_size: 2048 # 2 times of Perception Encoder hidden dim
  cls_mlp_layers: 2
  enable_patch_cls: True
  enable_cls_fusion: True
